/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApiErrorBody */
        ApiErrorBody: {
            /**
             * Code
             * @description `validation` · `unauthorized` · `forbidden` · `not_found` · `conflict` · `rate_limited` · `unavailable` · `internal`, plus business codes such as `seat_taken`, `hold_missing`, `too_many_seats`, `has_sales`.
             */
            code: string;
            /**
             * Details
             * @description Code-specific payload, e.g. `{taken: seat_id[]}` or `{fields: {path: msg}}`.
             */
            details?: {
                [key: string]: unknown;
            };
            /** Message */
            message: string;
        };
        /** ApiErrorResponse */
        ApiErrorResponse: {
            error: components["schemas"]["ApiErrorBody"];
        };
        /** Health */
        Health: {
            /** Ok */
            ok: boolean;
            /** Service */
            service: string;
            /** Version */
            version: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description Error envelope (06 §C) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
}
