/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Events */
        get: operations["list_events_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Event */
        get: operations["get_event_events__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/home": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Home */
        get: operations["home_home_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/showtimes/{showtime_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Showtime */
        get: operations["get_showtime_showtimes__showtime_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/showtimes/{showtime_id}/seats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Seats */
        get: operations["get_seats_showtimes__showtime_id__seats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/venues/{venue_id}/layout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Layout */
        get: operations["get_layout_venues__venue_id__layout_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApiErrorBody */
        ApiErrorBody: {
            /**
             * Code
             * @description `validation` · `unauthorized` · `forbidden` · `not_found` · `conflict` · `rate_limited` · `unavailable` · `internal`, plus business codes such as `seat_taken`, `hold_missing`, `too_many_seats`, `has_sales`.
             */
            code: string;
            /**
             * Details
             * @description Code-specific payload, e.g. `{taken: seat_id[]}` or `{fields: {path: msg}}`.
             */
            details?: {
                [key: string]: unknown;
            };
            /** Message */
            message: string;
        };
        /** ApiErrorResponse */
        ApiErrorResponse: {
            error: components["schemas"]["ApiErrorBody"];
        };
        /** EventCard */
        EventCard: {
            /** Duration Min */
            duration_min: number;
            /**
             * From Price Paise
             * @description Cheapest tier across upcoming showtimes.
             */
            from_price_paise: number | null;
            /** Genre */
            genre: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            next_showtime: components["schemas"]["NextShowtime"] | null;
            /** Poster Url */
            poster_url: string;
            /** Rating */
            rating: string | null;
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /**
             * Type
             * @enum {string}
             */
            type: "movie" | "concert";
            /**
             * Upcoming Count
             * @description Upcoming showtimes matching the list's date filter.
             */
            upcoming_count: number;
        };
        /** EventDetail */
        EventDetail: {
            /** Cast Lineup */
            cast_lineup: string[];
            /** Duration Min */
            duration_min: number;
            /**
             * From Price Paise
             * @description Cheapest tier across upcoming showtimes.
             */
            from_price_paise: number | null;
            /** Gallery Urls */
            gallery_urls: string[];
            /** Genre */
            genre: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            next_showtime: components["schemas"]["NextShowtime"] | null;
            /** Poster Url */
            poster_url: string;
            /** Rating */
            rating: string | null;
            /** Showtimes */
            showtimes: components["schemas"]["ShowtimeSummary"][];
            /** Slug */
            slug: string;
            /** Synopsis */
            synopsis: string;
            /** Title */
            title: string;
            /**
             * Type
             * @enum {string}
             */
            type: "movie" | "concert";
            /**
             * Upcoming Count
             * @description Upcoming showtimes matching the list's date filter.
             */
            upcoming_count: number;
        };
        /** EventList */
        EventList: {
            /** Events */
            events: components["schemas"]["EventCard"][];
            /** Genres */
            genres: components["schemas"]["FilterOption"][];
            /** Showtime Count */
            showtime_count: number;
            /** Total */
            total: number;
            /** Venues */
            venues: components["schemas"]["FilterOption"][];
        };
        /** FilterOption */
        FilterOption: {
            /** Count */
            count: number;
            /** Label */
            label: string;
            /** Value */
            value: string;
        };
        /** Health */
        Health: {
            /** Ok */
            ok: boolean;
            /** Service */
            service: string;
            /** Version */
            version: string;
        };
        /** HeldSeat */
        HeldSeat: {
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Seat Id */
            seat_id: string;
        };
        /** Home */
        Home: {
            /** Now Showing */
            now_showing: components["schemas"]["EventCard"][];
        };
        /** Layout */
        Layout: {
            /** Height */
            height: number;
            /** Sections */
            sections: components["schemas"]["LayoutSection"][];
            stage: components["schemas"]["LayoutStage"];
            /**
             * Template
             * @enum {string}
             */
            template: "grid" | "stalls_balcony" | "arena";
            /**
             * Tiers
             * @description `{key, label}` in price order, front to back — the legend.
             */
            tiers: components["schemas"]["LayoutTier"][];
            /** Width */
            width: number;
        };
        /** LayoutRow */
        LayoutRow: {
            /** Label */
            label: string;
            /** Seats */
            seats: components["schemas"]["LayoutSeat"][];
        };
        /** LayoutSeat */
        LayoutSeat: {
            /** Id */
            id: string;
            /** N */
            n: number;
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /** LayoutSection */
        LayoutSection: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Polygon */
            polygon?: number[][] | null;
            /** Rows */
            rows: components["schemas"]["LayoutRow"][];
            /**
             * Shape
             * @enum {string}
             */
            shape: "rows" | "wedge";
            /** Tier */
            tier: string;
        };
        /** LayoutStage */
        LayoutStage: {
            /** Label */
            label: string;
            /** W */
            w: number;
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /** LayoutTier */
        LayoutTier: {
            /** Key */
            key: string;
            /** Label */
            label: string;
        };
        /** NextShowtime */
        NextShowtime: {
            /**
             * Fill
             * @enum {string}
             */
            fill: "available" | "filling" | "sold_out";
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            /** Venue Name */
            venue_name: string;
        };
        /** SeatState */
        SeatState: {
            /**
             * Held
             * @description Held by someone else (not the caller).
             */
            held: components["schemas"]["HeldSeat"][];
            /**
             * Mine
             * @description Held by the caller's session.
             */
            mine: string[];
            /**
             * Server Time
             * Format: date-time
             */
            server_time: string;
            /** Sold */
            sold: string[];
            /**
             * V
             * @description State version; a diff with a lower `v` is stale.
             */
            v: number;
        };
        /** ShowtimeDetail */
        ShowtimeDetail: {
            event: components["schemas"]["ShowtimeEvent"];
            /**
             * Fee Paise
             * @description Convenience fee per ticket (03 R5: flat ₹30).
             */
            fee_paise: number;
            /**
             * Fill
             * @enum {string}
             */
            fill: "available" | "filling" | "sold_out";
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Layout Url
             * @description `/venues/{id}/layout` — immutable, cache it forever.
             */
            layout_url: string;
            /** Seats Left */
            seats_left: number;
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            /**
             * Status
             * @enum {string}
             */
            status: "scheduled" | "cancelled";
            /**
             * Tiers
             * @description Every tier of the venue with this show's price.
             */
            tiers: components["schemas"]["TierPrice"][];
            venue: components["schemas"]["ShowtimeVenue"];
        };
        /** ShowtimeEvent */
        ShowtimeEvent: {
            /** Duration Min */
            duration_min: number;
            /** Genre */
            genre: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Poster Url */
            poster_url: string;
            /** Rating */
            rating: string | null;
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /**
             * Type
             * @enum {string}
             */
            type: "movie" | "concert";
        };
        /** ShowtimeSummary */
        ShowtimeSummary: {
            /**
             * Fill
             * @enum {string}
             */
            fill: "available" | "filling" | "sold_out";
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Price Max Paise */
            price_max_paise: number;
            /** Price Min Paise */
            price_min_paise: number;
            /** Seats Left */
            seats_left: number;
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            /** Tiers */
            tiers: components["schemas"]["TierPrice"][];
            venue: components["schemas"]["VenueRef"];
        };
        /** ShowtimeVenue */
        ShowtimeVenue: {
            /** Address */
            address: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Photo Url */
            photo_url: string | null;
            /** Seat Count */
            seat_count: number;
            /**
             * Template
             * @enum {string}
             */
            template: "grid" | "stalls_balcony" | "arena";
        };
        /** TierPrice */
        TierPrice: {
            /** Label */
            label: string;
            /** Price Paise */
            price_paise: number;
            /** Tier Key */
            tier_key: string;
        };
        /** VenueRef */
        VenueRef: {
            /** Address */
            address: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Photo Url */
            photo_url: string | null;
            /** Seat Count */
            seat_count: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_events_events_get: {
        parameters: {
            query?: {
                /** @description today · tomorrow · weekend · YYYY-MM-DD (IST days) */
                date?: string | null;
                type?: ("movie" | "concert") | null;
                genre?: string | null;
                venue?: string | null;
                sort?: "soonest" | "price" | "title";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventList"];
                };
            };
            /** @description Error envelope (06 §C) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    get_event_events__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventDetail"];
                };
            };
            /** @description Error envelope (06 §C) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description Error envelope (06 §C) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    home_home_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Home"];
                };
            };
            /** @description Error envelope (06 §C) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    get_showtime_showtimes__showtime_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                showtime_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShowtimeDetail"];
                };
            };
            /** @description Error envelope (06 §C) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    get_seats_showtimes__showtime_id__seats_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                showtime_id: string;
            };
            cookie?: {
                fr_sid?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeatState"];
                };
            };
            /** @description Error envelope (06 §C) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    get_layout_venues__venue_id__layout_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                venue_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Layout"];
                };
            };
            /** @description Error envelope (06 §C) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
}
